# Generated by Django 4.0.1 on 2022-01-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.IntegerField()),
                ('password', models.CharField(default='', max_length=20)),
                ('rollno', models.IntegerField()),
                ('college', models.CharField(default='', max_length=30)),
                ('phoneno', models.IntegerField()),
            ],
        ),
    ]
